---
version: '3.7'
services:
  # Service image
  {{ cookiecutter.docker_application_tagname }}:
    image: {{ cookiecutter.project_slug }}:latest
    build: {{ cookiecutter.docker_application_dirname }}
    volumes:
      - type: bind
        source: .
        target: /{{ cookiecutter.docker_workspace_dirname }}
