---
version: '3.7'
services:
  # Service image
  app:
    image: {{ cookiecutter.project_slug }}:latest
    build: {{ cookiecutter.docker_application_dirname }}
    volumes:
      - type: bind
        source: .
        target: /workspace
